language: python
python:
  - "3.6.5"
  - "3.7.0"
dist: xenial
install:
  - pip install pipenv
  - pipenv install
script:
  - pipenv run python -m compileall ./cosobot.py
  - pipenv run python -m compileall ./cogs
  - pipenv run python ./cosobot.py --test
sudo: true
